### PR TITLE
add instructions on setting up a new install of OctoGAS

### PR DESCRIPTION
**Pull request by dreww**
adds step-by-step instructions on what is necessary to get a new octogas instance running

### CODE REVIEW

**Comment by dreww** [comment]
sorry about the bad branch name, i think i goofed up the fork and pull web flow

**Comment by mastahyeti** [comment]
Thanks for the PR. I feel like there should be an easier way to do this if you're just trying to setup an instance for yourself to use. Maybe by storing a personal access token in the script properties instead of setting up a whole OAuth app? Or, are you actually trying to setup a new instance that can be used by multiple people?

**Comment by dreww** [comment]
oh word, that makes sense - i was just trying to document what seemed to be necessary at the current state of things for a single person.

**Comment by mastahyeti** [comment]
Gotcha. I can come back later and try to make this flow easier. Thanks for the docs!

**Pull request merged**
